media:
  input: _src/assets
  output: /assets 
content:
  - name: meetings
    label: Meetings
    type: file
    path: _src/meetings.md
    fields:
      - name: meetings
        label: Meetings
        type: object
        list: false
        fields: 
          - name: label
            label: Label
            type: string
          - name: city
            label: City
            type: string
          - name: day
            label: Day
            type: string
          - name: time_start
            label: Start Time
            type: string
          - name: time_end
            label: End Time
            type: string
          - name: notes
            label: Notes
            type: text
          - name: address
            label: Address
            type: string
          - name: contact_name
            label: Contact Name
            type: string
          - name: contact_phone
            label: Contact Phone
            type: string
          - name: contact_email
            label: Contact Email
            type: string
          - name: location
            label: Location
            type: string
          - name: name
            label: Name
            type: string
          - name: contact_instructions
            label: Contact Instructions
            type: text
          - name: link_url
            label: Link URL
            type: string
            pattern: ^(https?:\/\/)?(www\.)?[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}(\/[^\s]*)?$
          - name: link_text
            label: Link Text
            type: string
  - name: news
    label: News
    type: collection
    path: _src/news
    view:
      fields: [ title, date ]
    fields:
       - name: title
         label: Title
         type: string
       - name: date
         label: Date
         type: date
       - name: excerpt
         label: Excerpt
         type: string
       - name: image
         label: Image
         type: image
       - name: body
         label: Body
         type: rich-text
         options:
           path: _src/assets
           extensions: [jpg, png, webp]

         