media:
  input: _src/assets
  output: /assets
content:
  - name: news
    label: News
    type: collection
    path: _src/news
    view:
      fields: [ title, date ]
    fields:
       - name: title
         label: Title
         type: string
       - name: date
         label: Date
         type: date
       - name: excerpt
         label: Excerpt
         type: string
       - name: image
         label: Image
         type: image
       - name: body
         label: Body
         type: rich-text
         options:
           path: _src/assets
           extensions: [jpg, png, webp]

         