---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: _src/news
  label: News
  create: all
  match: "**/*.md"
  templates:
  - news
- type: directory
  path: _src
  label: Pages
  create: all
  match: "**/*.md"
  exclude: _src/news
- type: document
  path: _src/_data/meetings.json
  label: Meeting List
upload_dir: _src/assets
public_path: "/assets"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: dist
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run forestry:preview
